import type { SmartAgent } from '../types'

export const INITIAL_CHARACTERS: SmartAgent[] = [
  {
    id: 'anhnld',
    name: 'AnhNLD',
    pos: { x: 0, y: 0 },
    target: { x: 0, y: 0 },
    state: 'idle',
    color: '#10a37f',
    spriteIdx: 0,
    path: [],
    targetNodeIdx: 0,
    statusText: 'THONG THẢ',
    statusIcon: null,
    delayUntil: 0,
    isResponding: false,
  },
  {
    id: 'ducdn',
    name: 'DucDN',
    pos: { x: 0, y: 0 },
    target: { x: 0, y: 0 },
    state: 'idle',
    color: '#22c55e',
    spriteIdx: 0,
    path: [],
    targetNodeIdx: 0,
    statusText: 'THONG THẢ',
    statusIcon: null,
    delayUntil: 0,
    isResponding: false,
  },
  {
    id: 'hieuvq',
    name: 'HieuVQ',
    pos: { x: 0, y: 0 },
    target: { x: 0, y: 0 },
    state: 'idle',
    color: '#f97316',
    spriteIdx: 0,
    path: [],
    targetNodeIdx: 0,
    statusText: 'THONG THẢ',
    statusIcon: null,
    delayUntil: 0,
    isResponding: false,
  },
  {
    id: 'nhibx',
    name: 'NhiBX',
    pos: { x: 0, y: 0 },
    target: { x: 0, y: 0 },
    state: 'idle',
    color: '#d97757',
    spriteIdx: 0,
    path: [],
    targetNodeIdx: 0,
    statusText: 'THONG THẢ',
    statusIcon: null,
    delayUntil: 0,
    isResponding: false,
  },
  {
    id: 'doanhlxq',
    name: 'DoanhLXQ',
    pos: { x: 0, y: 0 },
    target: { x: 0, y: 0 },
    state: 'idle',
    color: '#00a4ef',
    spriteIdx: 0,
    path: [],
    targetNodeIdx: 0,
    statusText: 'THONG THẢ',
    statusIcon: null,
    delayUntil: 0,
    isResponding: false,
  },
  {
    id: 'tinhdt',
    name: 'TinhDT',
    pos: { x: 0, y: 0 },
    target: { x: 0, y: 0 },
    state: 'idle',
    color: '#4d6eff',
    spriteIdx: 0,
    path: [],
    targetNodeIdx: 0,
    statusText: 'THONG THẢ',
    statusIcon: null,
    delayUntil: 0,
    isResponding: false,
  },
  {
    id: 'huynn',
    name: 'HuyNN',
    pos: { x: 0, y: 0 },
    target: { x: 0, y: 0 },
    state: 'idle',
    color: '#8e75ff',
    spriteIdx: 0,
    path: [],
    targetNodeIdx: 0,
    statusText: 'THONG THẢ',
    statusIcon: null,
    delayUntil: 0,
    isResponding: false,
  },
]
